const express = require("express")
const router = express.Router()
const indexPage = require("../controllers_view/controller_indexPage")
const travelsPage = require("../controllers_view/controller_travelsPage")
const travelsListPage = require("../controllers_view/controller_travelsListPage")
const strategyPage = require("../controllers_view/controller_strategyPage")
const strategyListPage = require("../controllers_view/controller_strategyListPage")
const loginPage = require("../controllers_view/controller_loginPage")
const registerPage = require("../controllers_view/controller_registerPage")
const memberPage = require("../controllers_view/controller_memberPage")
const addarticlePage = require("../controllers_view/controller_addarticlePage")
const detailPage = require("../controllers_view/controller_detailPage")
const askPage = require("../controllers_view/controller_askPage")
const answerPage = require("../controllers_view/controller_answerPage")
const newquestionPage = require("../controllers_view/controller_newquestionPage")
const userInfoUpdatePage = require("../controllers_view/controller_userInfoUpdatePage")
const editArticlePage = require("../controllers_view/controller_editArticlePage")
const searchMorePage = require("../controllers_view/controller_searchMorePage")
const changePasswordPage = require("../controllers_view/controller_changePasswordPage")

router
    .get("/",indexPage)
    .get("/index",indexPage)
    .get("/travels",travelsPage)
    .get("/travels/:id",travelsListPage)
    .get("/strategy",strategyPage)
    .get("/strategy/:id",strategyListPage)
    .get("/login",loginPage)
    .get("/register",registerPage)
    .get("/member",memberPage)
    .get("/addarticle",addarticlePage)
    .get("/detail/:id",detailPage)
    .get("/asks",askPage)
    .get("/answer/:id",answerPage)
    .get("/newquestion",newquestionPage)
    .get("/userInfoUpdate",userInfoUpdatePage)
    .get("/editArticle/:id",editArticlePage)
    .get("/searchMore/:type/:query",searchMorePage)
    .get("/changePassword",changePasswordPage)

module.exports = router